/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilSbStarRating {
        "disabled": boolean;
        "value": number;
    }
}
declare global {
    interface HTMLStencilSbStarRatingElement extends Components.StencilSbStarRating, HTMLStencilElement {
    }
    var HTMLStencilSbStarRatingElement: {
        prototype: HTMLStencilSbStarRatingElement;
        new (): HTMLStencilSbStarRatingElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-sb-star-rating": HTMLStencilSbStarRatingElement;
    }
}
declare namespace LocalJSX {
    interface StencilSbStarRating {
        "disabled"?: boolean;
        "value"?: number;
    }
    interface IntrinsicElements {
        "stencil-sb-star-rating": StencilSbStarRating;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-sb-star-rating": LocalJSX.StencilSbStarRating & JSXBase.HTMLAttributes<HTMLStencilSbStarRatingElement>;
        }
    }
}
