/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SbStarRating {
        "disabled": boolean;
        "value": number;
    }
}
declare global {
    interface HTMLSbStarRatingElement extends Components.SbStarRating, HTMLStencilElement {
    }
    var HTMLSbStarRatingElement: {
        prototype: HTMLSbStarRatingElement;
        new (): HTMLSbStarRatingElement;
    };
    interface HTMLElementTagNameMap {
        "sb-star-rating": HTMLSbStarRatingElement;
    }
}
declare namespace LocalJSX {
    interface SbStarRating {
        "disabled"?: boolean;
        "value"?: number;
    }
    interface IntrinsicElements {
        "sb-star-rating": SbStarRating;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sb-star-rating": LocalJSX.SbStarRating & JSXBase.HTMLAttributes<HTMLSbStarRatingElement>;
        }
    }
}
